// packages/sdks/react-sdk/examples/app/Login.tsx
/* eslint-disable no-console */
import React, { useCallback, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Descope, useSession } from '../../src';

const Login = () => {
  const [errorMessage, setErrorMessage] = useState('');
  const [isFlowLoading, setIsFlowLoading] = useState(true);

  const { isAuthenticated, isSessionLoading } = useSession();
  const navigate = useNavigate();

  useEffect(() => {
    if (isAuthenticated) {
      navigate('/');
    }
  }, [navigate, isAuthenticated]);

  const onSuccess = useCallback(() => {
    navigate('/');
  }, [navigate]);

  const onError = useCallback(() => {
    setErrorMessage('Something went wrong');
  }, [setErrorMessage]);

  const onReady = useCallback(() => {
    setIsFlowLoading(false);
  }, [setIsFlowLoading]);

  const errorTransformer = useCallback(
    (error: { text: string; type: string }) => {
      console.log('@@@ errorTransformer', {
        text, type
      });
      const translationMap = {
        SAMLStartFailed: 'Failed to start SAML flow',
      };
      return translationMap[error.type] || error.text;
    },
    [],
  );

  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
      }}
    >
      <h2>Login</h2>
      {(isSessionLoading || isFlowLoading) && <div>Loading...</div>}
      {!isSessionLoading && (
        <Descope
          flowId={process.env.DESCOPE_FLOW_ID || 'sign-up-or-in'}
          onSuccess={onSuccess}
          onError={onError}
          onReady={onReady}
          // form={{ email: 'predefinedname@domain.com' }} // found in context key: form.email
          client={{ version: '1.0.2' }} // found in context key: client.version
          debug={true}
          theme={process.env.DESCOPE_THEME as any}
          locale={process.env.DESCOPE_LOCALE as string}
          redirectUrl={process.env.DESCOPE_REDIRECT_URL}
          tenant={process.env.DESCOPE_TENANT_ID}
          telemetryKey={process.env.DESCOPE_TELEMETRY_KEY}
          errorTransformer={errorTransformer}
        />
      )}
      {errorMessage && (
        <div
          className="error"
          style={{
            margin: 'auto',
            color: 'red',
          }}
        >
          {errorMessage}
        </div>
      )}
    </div>
  );
};

export default Login;

// packages/sdks/vue-sdk/example/components/Login.vue
<!-- eslint-disable vue/multi-word-component-names -->
<template>
  <div class="login-wrapper">
    <p v-if="isLoading || isFlowLoading">Loading...</p>
    <div v-else-if="isAuthenticated">
      <h1>You are authenticated</h1>
    </div>
    <Descope
      :flowId="flowId"
      @success="handleSuccess"
      @error="handleError"
      @ready="handleReady"
      :errorTransformer="errorTransformer"
      :form="form"
      :client="client"
    />
  </div>
</template>

<script setup>
import { Descope, useSession } from '../../src';
import { ref } from 'vue';
import { useRouter } from 'vue-router';
const router = useRouter();
const isFlowLoading = ref(true);

const handleError = (e) => {
  console.log('Got error', e);
};

const handleReady = () => {
  isFlowLoading.value = false;
};

const handleSuccess = (e) => {
  console.log('Logged in', e);
  router.push({ path: '/' });
};

const errorTransformer = (error) => {
  const translationMap = {
    SAMLStartFailed: 'Failed to start SAML flow',
  };
  return translationMap[error.type] || error.text;
};

const { isLoading, isAuthenticated } = useSession();
const flowId = process.env.VUE_APP_DESCOPE_FLOW_ID || 'sign-up-or-in';
const form = {}; // { email: 'myemail@domain.com' }; // found in context key: form.email
const client = { version: '1.0.1' }; // found in context key: client.version
</script>

<style>
.login-wrapper {
  margin: 20px;
  align-self: center;
  max-width: 500px;
}
</style>
