// packages/sdks/nextjs-sdk/examples/app-router/app/manage-roles/page.tsx
import { RoleManagement } from '@descope/nextjs-sdk';
import React from 'react';

export default () => {
	return (
		<div
			style={{
				display: 'flex',
				flexDirection: 'column',
				alignItems: 'center',
				justifyContent: 'center'
			}}
		>
			<h1>Manage Roles</h1>
			<RoleManagement
				tenant={process.env.NEXT_PUBLIC_DESCOPE_TENANT}
				widgetId="role-management-widget"
			/>
		</div>
	);
};

// packages/sdks/vue-sdk/example/components/ManageRoles.vue
<!-- eslint-disable vue/multi-word-component-names -->
<template>
	<div class="manage-roles-wrapper">
		<h1>Manage Roles</h1>
		<RoleManagement :tenant="tenant" widget-id="role-management-widget" />
	</div>
</template>

<script setup>
import { RoleManagement } from '../../src';

const tenant = process.env.VUE_APP_DESCOPE_TENANT;
</script>

<style>
.manage-roles-wrapper {
	margin: 20px;
}
</style>
