// packages/sdks/nextjs-sdk/examples/app-router/app/my-user-profile/page.tsx
'use client';

import React from 'react';
import { UserProfile } from '@descope/nextjs-sdk'; // eslint-disable-line

export default () => (
	<div
		style={{
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'center',
			justifyContent: 'center'
		}}
	>
		<h1>User Profile</h1>
		<UserProfile
			widgetId="user-profile-widget"
			onLogout={() => {
				window.location.href = '/login';
			}}
		/>
	</div>
);

// packages/sdks/vue-sdk/example/components/MyUserProfile.vue
<!-- eslint-disable vue/multi-word-component-names -->
<template>
  <div class="user-profile-wrapper">
    <h1>User Profile</h1>
    <UserProfile @logout="onLogout" widget-id="user-profile-widget" />
  </div>
</template>

<script setup>
import { UserProfile } from '../../src';

const onLogout = () => (window.location.href = '/login');
</script>

<style>
.user-profile-wrapper {
  margin: 20px;
}
</style>
