// packages/sdks/react-sdk/examples/app/Login.tsx
/* eslint-disable no-console */
import React, { useCallback, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Descope, useSession } from '../../src';

const Login = () => {
  const [errorMessage, setErrorMessage] = useState('');
  const [isFlowLoading, setIsFlowLoading] = useState(true);

  const { isAuthenticated, isSessionLoading } = useSession();
  const navigate = useNavigate();

  useEffect(() => {
    if (isAuthenticated) {
      navigate('/');
    }
  }, [navigate, isAuthenticated]);

  const onSuccess = useCallback(() => {
    navigate('/');
  }, [navigate]);

  const onError = useCallback(() => {
    setErrorMessage('Something went wrong');
  }, [setErrorMessage]);

  const onReady = useCallback(() => {
    setIsFlowLoading(false);
  }, [setIsFlowLoading]);

  const errorTransformer = useCallback(
    (error: { text: string; type: string }) => {
      console.log('@@@ errorTransformer', {
        text, type
      });
      const translationMap = {
        SAMLStartFailed: 'Failed to start SAML flow',
      };
      return translationMap[error.type] || error.text;
    },
    [],
  );

  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
      }}
    >
      <h2>Login</h2>
      {(isSessionLoading || isFlowLoading) && <div>Loading...</div>}
      {!isSessionLoading && (
        <Descope
          flowId={process.env.DESCOPE_FLOW_ID || 'sign-up-or-in'}
          onSuccess={onSuccess}
          onError={onError}
          onReady={onReady}
          // form={{ email: 'predefinedname@domain.com' }} // found in context key: form.email
          client={{ version: '1.0.2' }} // found in context key: client.version
          debug={true}
          theme={process.env.DESCOPE_THEME as any}
          locale={process.env.DESCOPE_LOCALE as string}
          redirectUrl={process.env.DESCOPE_REDIRECT_URL}
          tenant={process.env.DESCOPE_TENANT_ID}
          telemetryKey={process.env.DESCOPE_TELEMETRY_KEY}
          errorTransformer={errorTransformer}
        />
      )}
      {errorMessage && (
        <div
          className="error"
          style={{
            margin: 'auto',
            color: 'red',
          }}
        >
          {errorMessage}
        </div>
      )}
    </div>
  );
};

export default Login;

// packages/sdks/angular-sdk/projects/demo-app/src/app/login/login.component.ts
/* eslint-disable no-console */
import { Component } from '@angular/core';
import { environment } from '../../environments/environment';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html'
})
export class LoginComponent {
  flowId = environment.descopeFlowId ?? 'sign-up-or-in';
  theme = (environment.descopeTheme as 'light' | 'dark' | 'os') ?? 'os';
  telemetryKey = environment.descopeTelemetryKey ?? '';
  debugMode = environment.descopeDebugMode ?? false;
  tenantId = environment.descopeTenantId ?? '';
  locale = environment.descopeLocale ?? '';
  redirectUrl = environment.descopeRedirectUrl ?? '';

  isLoading = true;

  constructor(private router: Router) {}

  errorTransformer = (error: { text: string; type: string }): string => {
    const translationMap: { [key: string]: string } = {
      SAMLStartFailed: 'Failed to start SAML flow'
    };
    return translationMap[error.type] || error.text;
  };

  onSuccess(e: CustomEvent) {
    console.log('SUCCESSFULLY LOGGED IN FROM WEB COMPONENT', e.detail);
    this.router.navigate(['/']).catch((err) => console.error(err));
  }

  onError(e: CustomEvent) {
    console.log('ERROR FROM LOG IN FLOW FROM WEB COMPONENT', e);
  }

  onReady() {
    this.isLoading = false;
  }
}

<descope
  (success)="onSuccess($event)"
  (error)="onError($event)"
  (ready)="onReady()"
  [theme]="theme"
  [flowId]="flowId"
  [locale]="locale"
  [redirectUrl]="redirectUrl"
  [telemetryKey]="telemetryKey"
  [tenant]="tenantId"
  [debug]="debugMode"
  [errorTransformer]="errorTransformer"
></descope>
<div
  *ngIf="isLoading"
  class="loading-indicator"
  style="display: flex; justify-content: center; align-items: center"
>
  Loading...
</div>
