// packages/sdks/vue-sdk/example/components/ManageAudit.vue
<!-- eslint-disable vue/multi-word-component-names -->
<template>
  <div class="manage-audit-wrapper">
    <h1>Manage Audit</h1>
    <AuditManagement :tenant="tenant" widget-id="audit-management-widget" />
  </div>
</template>

<script setup>
import { AuditManagement } from '../../src';

const tenant = process.env.VUE_APP_DESCOPE_TENANT;
</script>

<style>
.manage-audit-wrapper {
  margin: 20px;
}
</style>

// packages/sdks/nextjs-sdk/examples/app-router/app/manage-audit/page.tsx
import React from 'react';
import { AuditManagement } from '@descope/nextjs-sdk'; // eslint-disable-line

export default () => (
	<div
		style={{
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'center',
			justifyContent: 'center'
		}}
	>
		<h1>Manage Audit</h1>
		<AuditManagement
			tenant={process.env.NEXT_PUBLIC_DESCOPE_TENANT}
			widgetId="audit-management-widget"
		/>
	</div>
);
