// packages/sdks/vue-sdk/example/components/ManageUsers.vue
<!-- eslint-disable vue/multi-word-component-names -->
<template>
  <div class="manage-users-wrapper">
    <h1>Manage Users</h1>
    <UserManagement :tenant="tenant" widget-id="user-management-widget" />
  </div>
</template>

<script setup>
import { UserManagement } from '../../src';

const tenant = process.env.VUE_APP_DESCOPE_TENANT;
</script>

<style>
.manage-users-wrapper {
  margin: 20px;
}
</style>

// packages/sdks/nextjs-sdk/examples/app-router/app/manage-users/page.tsx
import { UserManagement } from '@descope/nextjs-sdk';
import React from 'react';

export default () => {
	return (
		<div
			style={{
				display: 'flex',
				flexDirection: 'column',
				alignItems: 'center',
				justifyContent: 'center'
			}}
		>
			<h1>Manage Users</h1>
			<UserManagement
				tenant={process.env.NEXT_PUBLIC_DESCOPE_TENANT}
				widgetId="user-management-widget"
			/>
		</div>
	);
};
