// packages/sdks/react-sdk/src/components/ApplicationsPortal.tsx
import React, {
  lazy,
  Suspense,
  useEffect,
  useImperativeHandle,
  useState,
} from 'react';
import Context from '../hooks/Context';
import { ApplicationsPortalProps } from '../types';

// web-component code uses browser API, but can be used in SSR apps, hence the lazy loading
const ApplicationsPortalWC = lazy(async () => {
  await import('@descope/applications-portal-widget');

  return {
    default: ({
      projectId,
      baseUrl,
      baseStaticUrl,
      innerRef,
      widgetId,
      theme,
      debug,
      styleId,
    }) => (
	<descope-applications-portal-widget
        project-id={projectId}
        widget-id={widgetId}
        base-url={baseUrl}
        base-static-url={baseStaticUrl}
        theme={theme}
        debug={debug}
        style-id={styleId}
        ref={innerRef}
      />
    ),
  };
});

const ApplicationsPortal: React.ForwardRefExoticComponent<
  ApplicationsPortalProps & React.RefAttributes<HTMLElement>
> = React.forwardRef<HTMLElement, ApplicationsPortalProps>(
  ({ logger, theme, debug, widgetId, styleId }, ref) => {
    const [innerRef, setInnerRef] = useState(null);

    useImperativeHandle(ref, () => innerRef);

    const { projectId, baseUrl, baseStaticUrl } = React.useContext(Context);

    useEffect(() => {
      if (innerRef && logger) {
        innerRef.logger = logger;
      }
    }, [innerRef, logger]);
    return (
	<Suspense fallback={null}>
		<ApplicationsPortalWC
          projectId={projectId}
          widgetId={widgetId}
          baseUrl={baseUrl}
          baseStaticUrl={baseStaticUrl}
          innerRef={setInnerRef}
          theme={theme}
          debug={debug}
          styleId={styleId}
        />
	</Suspense>
    );
  },
);

export default ApplicationsPortal;

// packages/sdks/vue-sdk/src/ApplicationsPortal.vue
<!-- eslint-disable vue/multi-word-component-names -->
<template>
  <div>
    <descope-applications-portal-widget
      :project-id="projectId"
      :base-url="baseUrl"
      :base-static-url="baseStaticUrl"
      :theme.attr="theme"
      :debug.attr="debug"
      :widget-id="widgetId"
      :style-id="styleId"
    />
  </div>
</template>

<script setup lang="ts">
import '@descope/applications-portal-widget';
import { useOptions } from './hooks';

defineProps({
  widgetId: {
    type: String,
    required: true,
  },
  theme: {
    type: String,
  },
  styleId: {
    type: String,
  },
  debug: {
    type: Boolean,
  },
});

const { projectId, baseUrl, baseStaticUrl } = useOptions();
</script>
