// packages/sdks/solid-sdk/src/Descope.tsx
import { onMount, onCleanup, createSignal, Show, type JSX } from 'solid-js';
import { isServer } from 'solid-js/web';
import { useDescopeContext } from './hooks';
import type { DescopeProps } from './types';
import { baseHeaders } from './constants';
import { getGlobalSdk } from './sdk';

export function Descope(props: DescopeProps): JSX.Element {
  let ref: HTMLElement | undefined;
  const [, setIsLoaded] = createSignal(false);
  const context = useDescopeContext();

  onMount(async () => {
    if (isServer || !ref) return;

    await import('@descope/web-component');

    const DescopeWc = customElements.get('descope-wc');
    if (DescopeWc) {
      (DescopeWc as any).sdkConfigOverrides = {
        baseHeaders,
        persistTokens: false,
        hooks: {
          get beforeRequest() {
            return getGlobalSdk()?.httpClient?.hooks?.beforeRequest;
          },
          set beforeRequest(_) {},
        },
      };
    }

    const handleSuccess = async (e: Event) => {
      const customEvent = e as CustomEvent;
      if (context.sdk?.httpClient?.hooks?.afterRequest) {
        await context.sdk.httpClient.hooks.afterRequest(
          {} as any,
          new Response(JSON.stringify(customEvent.detail)),
        );
      }
      props.onSuccess?.(customEvent);
    };

    const handleError = (e: Event) => {
      props.onError?.(e as CustomEvent);
    };

    const handleReady = (e: Event) => {
      setIsLoaded(true);
      props.onReady?.(e as CustomEvent);
    };

    ref.addEventListener('success', handleSuccess);
    ref.addEventListener('error', handleError);
    ref.addEventListener('ready', handleReady);

    onCleanup(() => {
      ref?.removeEventListener('success', handleSuccess);
      ref?.removeEventListener('error', handleError);
      ref?.removeEventListener('ready', handleReady);
    });
  });

  return (
    <Show when={!isServer} fallback={<div>Loading...</div>}>
      <form>
        <descope-wc
          ref={ref}
          project-id={context.projectId}
          flow-id={props.flowId}
          base-url={context.baseUrl}
          base-static-url={context.baseStaticUrl}
          base-cdn-url={context.baseCdnUrl}
          theme={props.theme}
          locale={props.locale}
          nonce={props.nonce}
          tenant={props.tenant}
          auto-focus={props.autoFocus}
          validate-on-blur={props.validateOnBlur}
          restart-on-error={props.restartOnError}
          debug={props.debug}
          telemetry-key={props.telemetryKey}
          redirect-url={props.redirectUrl}
          outbound-app-id={props.outboundAppId}
          outbound-app-scopes={props.outboundAppScopes}
          popup-origin={props.popupOrigin}
          style-id={props.styleId}
          dismiss-screen-error-on-input={props.dismissScreenErrorOnInput}
          store-last-authenticated-user={context.storeLastAuthenticatedUser}
          keep-last-authenticated-user-after-logout={
            context.keepLastAuthenticatedUserAfterLogout
          }
          refresh-cookie-name={context.refreshCookieName}
          external-request-id={props.externalRequestId}
          form={JSON.stringify(props.form)}
          client={JSON.stringify(props.client)}
          error-transformer={props.errorTransformer as any}
          logger={props.logger as any}
          on-screen-update={props.onScreenUpdate as any}
          custom-storage={context.customStorage as any}
        >
          {props.children}
        </descope-wc>
      </form>
    </Show>
  );
}

export function SignInFlow(props: Omit<DescopeProps, 'flowId'>): JSX.Element {
  return <Descope flowId="sign-in" {...props} />;
}

export function SignUpFlow(props: Omit<DescopeProps, 'flowId'>): JSX.Element {
  return <Descope flowId="sign-up" {...props} />;
}

export function SignUpOrInFlow(
  props: Omit<DescopeProps, 'flowId'>,
): JSX.Element {
  return <Descope flowId="sign-up-or-in" {...props} />;
}

// packages/sdks/vue-sdk/src/Descope.vue
<!-- eslint-disable vue/multi-word-component-names -->
<template>
  <div>
    <descope-wc
      :project-id="projectId"
      :base-url="baseUrl"
      :base-static-url="baseStaticUrl"
      :base-cdn-url="baseCdnUrl"
      :flow-id="flowId"
      :theme.attr="theme"
      :locale.attr="locale"
      :tenant.attr="tenant"
      :debug.attr="debug"
      :telemetryKey.attr="telemetryKey"
      :redirect-url="redirectUrl"
      :auto-focus="autoFocus"
      :style-id="styleId"
      :validate-on-blur="validateOnBlur"
      :restart-on-error="restartOnError"
      :store-last-authenticated-user="storeLastAuthenticatedUser"
      :customStorage.prop="customStorage"
      :errorTransformer.prop="errorTransformer"
      :onScreenUpdate.prop="onScreenUpdate"
      :form.attr="formStr"
      :client.attr="clientStr"
      :nonce.attr="nonce"
      :dismiss-screen-error-on-input.attr="dismissScreenErrorOnInput"
      :popup-origin.attr="popupOrigin"
      @success="onSuccess"
      @error="onError"
      @ready="onReady"
    >
      <slot></slot>
    </descope-wc>
  </div>
</template>

<script setup lang="ts">
import DescopeWcClass from '@descope/web-component';
import { useOptions, useDescope } from './hooks';
import { baseHeaders } from './constants';
import { RequestConfig } from '@descope/core-js-sdk';
import { computed } from 'vue';
import { getGlobalSdk } from './sdk';
import type { JWTResponse, ErrorResponse } from './types';

const WebComponent: any = customElements?.get('descope-wc') || DescopeWcClass;

WebComponent.sdkConfigOverrides = {
  // Overrides the web-component's base headers to indicate usage via the React SDK
  baseHeaders,
  // Disables token persistence within the web-component to delegate token management
  // to the global SDK hooks. This ensures token handling aligns with the SDK's configuration,
  // and web-component requests leverage the global SDK's beforeRequest hooks for consistency
  persistTokens: false,
  hooks: {
    get beforeRequest() {
      // Retrieves the beforeRequest hook from the global SDK, which is initialized
      // within the AuthProvider using the desired configuration. This approach ensures
      // the web-component utilizes the same beforeRequest hooks as the global SDK
      return getGlobalSdk().httpClient.hooks.beforeRequest;
    },
    set beforeRequest(_) {
      // The empty setter prevents runtime errors when attempts are made to assign a value to 'beforeRequest'.
      // JavaScript objects default to having both getters and setters
    },
  },
};

const props = defineProps({
  flowId: {
    type: String,
    required: true,
  },
  tenant: {
    type: String,
  },
  theme: {
    type: String,
  },
  locale: {
    type: String,
  },
  debug: {
    type: Boolean,
  },
  telemetryKey: {
    type: String,
  },
  redirectUrl: {
    type: String,
  },
  autoFocus: {
    type: Boolean || String,
  },
  validateOnBlur: {
    type: Boolean,
  },
  restartOnError: {
    type: Boolean,
  },
  errorTransformer: {
    type: Function,
  },
  onScreenUpdate: {
    type: Function,
  },
  form: {
    type: Object,
  },
  client: {
    type: Object,
  },
  styleId: {
    type: String,
  },
  nonce: {
    type: String,
  },
  dismissScreenErrorOnInput: {
    type: Boolean,
  },
  popupOrigin: {
    type: String,
  },
});
// const emit = defineEmits(['success', 'error', 'ready']);
const emit = defineEmits<{
  (e: 'success', payload: CustomEvent<JWTResponse>): void;
  (e: 'error', payload: CustomEvent<ErrorResponse>): void;
  (e: 'ready', payload: CustomEvent<Record<string, never>>): void;
}>();
const {
  projectId,
  baseUrl,
  baseStaticUrl,
  storeLastAuthenticatedUser,
  baseCdnUrl,
  customStorage,
} = useOptions();
const sdk = useDescope();

const formStr = computed(() => (props.form ? JSON.stringify(props.form) : ''));
const clientStr = computed(() =>
  props.client ? JSON.stringify(props.client) : '',
);
const onSuccess = async (e: CustomEvent<JWTResponse>) => {
  await sdk.httpClient.hooks?.afterRequest?.(
    {} as RequestConfig,
    new Response(JSON.stringify(e.detail)),
  );
  emit('success', e);
};

const onError = (e: CustomEvent<ErrorResponse>) => emit('error', e);

const onReady = (e: CustomEvent<Record<string, never>>) => emit('ready', e);
</script>
