// packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/user-profile/user-profile.component.ts
import {
  Component,
  ElementRef,
  EventEmitter,
  Input,
  Output,
  Inject,
  PLATFORM_ID
} from '@angular/core';
import { DescopeAuthConfig, ILogger } from '../../types/types';
import { DescopeAuthService } from '../../services/descope-auth.service';
import { BaseLazyWidgetComponent } from '../../base/base-lazy-widget.component';

@Component({
  selector: 'user-profile',
  standalone: true,
  template: ''
})
export class UserProfileComponent extends BaseLazyWidgetComponent {
  projectId: string;
  baseUrl?: string;
  baseStaticUrl?: string;
  baseCdnUrl?: string;
  @Input() widgetId: string;

  @Input() theme: 'light' | 'dark' | 'os';

  @Input() locale: string;
  @Input() debug: boolean;
  @Input() logger: ILogger;
  @Input() styleId: string;

  @Output() logout: EventEmitter<CustomEvent> = new EventEmitter<CustomEvent>();

  @Output() ready: EventEmitter<void> = new EventEmitter<void>();

  @Output() toast: EventEmitter<CustomEvent> = new EventEmitter<CustomEvent>();

  constructor(
    elementRef: ElementRef,
    descopeConfig: DescopeAuthConfig,
    private descopeAuthService: DescopeAuthService,
    @Inject(PLATFORM_ID) platformId: object
  ) {
    super(elementRef, platformId);
    this.projectId = descopeConfig.projectId;
    this.baseUrl = descopeConfig.baseUrl;
    this.baseStaticUrl = descopeConfig.baseStaticUrl;
    this.baseCdnUrl = descopeConfig.baseCdnUrl;
  }

  protected async loadWidget(): Promise<HTMLElement | null> {
    try {
      const WidgetModule = await import('@descope/user-profile-widget');
      const DescopeUserProfileWidget = WidgetModule.default;
      return new DescopeUserProfileWidget() as unknown as HTMLElement;
    } catch (error) {
      // eslint-disable-next-line no-console
      console.error('Failed to load User Profile widget:', error);
      return null;
    }
  }

  protected setupWebComponent() {
    if (!this.webComponent) return;

    this.webComponent.setAttribute('project-id', this.projectId);
    this.webComponent.setAttribute('widget-id', this.widgetId);
    if (this.baseUrl) {
      this.webComponent.setAttribute('base-url', this.baseUrl);
    }
    if (this.baseStaticUrl) {
      this.webComponent.setAttribute('base-static-url', this.baseStaticUrl);
    }
    if (this.baseCdnUrl) {
      this.webComponent.setAttribute('base-cdn-url', this.baseCdnUrl);
    }
    if (this.theme) {
      this.webComponent.setAttribute('theme', this.theme);
    }
    if (this.locale) {
      this.webComponent.setAttribute('locale', this.locale);
    }
    if (this.debug) {
      this.webComponent.setAttribute('debug', this.debug.toString());
    }
    if (this.styleId) {
      this.webComponent.setAttribute('style-id', this.styleId);
    }

    if (this.logger) {
      (this.webComponent as any).logger = this.logger;
    }
  }

  protected setupEventListeners(): void {
    if (!this.webComponent) return;

    this.webComponent.addEventListener('logout', (e: Event) => {
      this.logout?.emit(e as CustomEvent);
      this.descopeAuthService.setSession('');
      this.descopeAuthService.setIsAuthenticated(false);
      this.descopeAuthService.setUser(null);
    });
    if (this.ready) {
      this.webComponent.addEventListener('ready', () => {
        this.ready?.emit();
      });
    }

    this.webComponent.addEventListener('toast', (e: Event) => {
      this.toast?.emit(e as CustomEvent);
    });
  }
}

// packages/sdks/vue-sdk/src/UserProfile.vue
<!-- eslint-disable vue/multi-word-component-names -->
<template>
  <div>
    <descope-user-profile-widget
      :project-id="projectId"
      :base-url="baseUrl"
      :base-static-url="baseStaticUrl"
      :base-cdn-url="baseCdnUrl"
      :theme.attr="theme"
      :locale.attr="locale"
      :debug.attr="debug"
      :widget-id="widgetId"
      :style-id="styleId"
      @logout="onLogout"
      @ready="onReady"
      @toast="onToast"
    />
  </div>
</template>

<script setup lang="ts">
import { inject } from 'vue';
import { DESCOPE_INJECTION_KEY } from './constants';
import '@descope/user-profile-widget';
const descope = inject(DESCOPE_INJECTION_KEY);
import { useOptions } from './hooks';
const emit = defineEmits<{
  (e: 'logout', payload: Event): void;
  (e: 'ready', payload: CustomEvent<Record<string, never>>): void;
  (
    e: 'toast',
    payload: CustomEvent<{
      message: string;
      detail?: string;
      severity: 'success' | 'error';
    }>,
  ): void;
}>();

const onLogout = (e: Event) => {
  descope?.resetAuth(); // reset session values
  emit('logout', e);
};

const onReady = (e: CustomEvent<Record<string, never>>) => emit('ready', e);
const onToast = (
  e: CustomEvent<{
    message: string;
    detail?: string;
    severity: 'success' | 'error';
  }>,
) => emit('toast', e);

defineProps({
  widgetId: {
    type: String,
    required: true,
  },
  theme: {
    type: String,
  },
  locale: {
    type: String,
  },
  styleId: {
    type: String,
  },
  debug: {
    type: Boolean,
  },
});

const { projectId, baseUrl, baseStaticUrl, baseCdnUrl } = useOptions();
</script>
